name: Build and Push Docker Images

on:
  workflow_call:

env:
  REGISTRY: ghcr.io  # Hardcoded registry
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Download Dockerfile from reusable workflow repository
        run: |
          # Set the repository and path to the Dockerfile
          WORKFLOW_REPO="gradinamax-software/github-actions-templates"
          DOCKERFILE_PATH=".github/docker/Dockerfile"

          git clone --no-checkout https://github.com/$WORKFLOW_REPO.git workflow-repo
          cd workflow-repo
          git checkout origin/main -- $DOCKERFILE_PATH
          cd ..

          # Copy the Dockerfile to the current directory
          cp workflow-repo/$DOCKERFILE_PATH ./Dockerfile

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
